### ISSUE TITLE
Iterator count mismatch for time bucket queries when data is loaded from disk

### ISSUE THREAD

**Issue by black-adder** [xichen2020/eventdb#148]
Running a simple time bucket query like: `{"namespace":"service","start_time":1551296381,"end_time":1551297381,"time_unit":"1s","time_granularity":"1m"}` will fail if none of the segments are in memory with the following error:

`error performing time bucket query {service 1551293338000000000 1551294438000000000 1m0s [] map[12889413958949747480:{[@timestamp] map[0:map[time:{}]]}]} against database namespace service: error iterating over timestamp data: doc ID iterator and the position iterator iterator count mismatch"}`

If you run the query against data in memory, the query succeeds.

**Comment by notbdu** [comment]
This is similar to what I saw in a poorly named issue: #144.
A fix is out in PR #142.
