### ISSUE TITLE
Benchmarking gozstd library performance

### ISSUE THREAD

**Issue by xichen2020** [xichen2020/eventdb#99]
cc @notbdu @black-adder 

We should benchmark the compression/decompression speed of the gozstd library since it's likely 2x - 10x slower than the native algorithm.

**Comment by notbdu** [comment]
testdata:
265 MB rtapi logs
100k log lines

gozstd performance:
~1.08 seconds compression to file
~.24 seconds decompression in memory

zstd cli performance:
~.86 seconds compression to file
~.269 seconds decompression to `/dev/null`

**Comment by xichen2020** [comment]
Just a sanity check, have we verified that the decompressed data are the same as the uncompressed data? Seemed a bit surprising that the cgo version is just as fast as the native version.

**Comment by notbdu** [comment]
The data sizes were the same but I didn't checksum the files. Let me do that.

**Comment by notbdu** [comment]
Updated results:
279 MB rtapi log data (100k log lines)
36 MB compressed

~ 250 MB / s decompression
~ 1 GB / s compression

Added results in comment form to the benchmarks themselves.
